import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import SheetProvider from "@/providers/sheet-provider";
import { QueryProvider } from "@/providers/query-provider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import TaskBoardComponent from "@/components/TaskBoardComponent";
import { Toaster } from "@/components/ui/sonner"
import { redirect } from "next/navigation";


const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={outfit.className} >
          <QueryProvider>
            <SheetProvider />
            <Toaster richColors position="top-center"/>
            <div className="w-screen h-screen flex flex-col justify-center overflow-x-hidden">
             {session !== null && <TaskBoardComponent />}
              {children}
            </div>
          </QueryProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
